// background_remover/src/components/HomeCard/Text.tsx

function Text({href, title, desc}: {href: string, title: string, desc: string}) {
  return (
    <>
        <a href={href}>
            <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{ title }</h5>
        </a>
        <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">{ desc }</p>
    </>
  )
}

export default Text

// frontend/src/components/HomeCard/components/Text.vue
<script>
    export default {
        props: {
            href: String,
            title: String,
            desc: String
        }
    }
</script>

<template>
    <a :href="href">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ title }}</h5>
    </a>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ desc }}</p>
</template>
