// background_remover/src/components/ImageOutputCard/Index.tsx
import DownloadButton from "./DownloadButton"

function Index({imageSrc}: {imageSrc?: string}) {

    const handleDownloadClick = () => {
        if (imageSrc) {
            const link = document.createElement('a');
            link.download = `${imageSrc.split('/').pop()?.split('?')[0]}.png`;
            link.href = imageSrc;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        }
    }

  return (
    <>
        <figure className="max-w-lg">
            <img className="h-auto max-w-full rounded-lg" src={imageSrc} alt="image" />
        </figure>
        <DownloadButton onClick={handleDownloadClick} />
    </>
  )
}

export default Index

// frontend/src/components/ImageOutputCard/ImageOutputCard.vue
<script>
    import DownloadButton from './components/DownloadButton.vue';

    export default {
        components: {
            DownloadButton
        },
        props: {
            imageSrc: String
        }, 
        methods: {
            handleDownloadClick() {
                const link = document.createElement('a');
                link.download = `${this.imageSrc.split('/').pop().split('?')[0]}.png`;
                link.href = this.imageSrc;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
            }
        }
    }
</script>

<template>
    <div>       
        <figure class="max-w-lg">
            <img class="h-auto max-w-full rounded-lg" :src="imageSrc" alt="image">
        </figure>
        <DownloadButton @click="handleDownloadClick" />
    </div>
</template>
