// frontend/src/components/HomeCard/components/Card.vue
<script>
    import Text from './Text.vue';
    import Button from './Button.vue';
    import LoginModal from '../../LoginModal/LoginModal.vue';
    import { RouterLink } from 'vue-router';

    export default {
        props: {
            title: String,
            desc: String,
            buttonText: String,
            isForLogin: {
                type: Boolean,
                default: false
            },
            href: String,
        },
        components: {
            Text,
            Button,
            LoginModal,
            RouterLink
        }
    }
</script>

<template>
    <article class="max-w-lg md:max-w-xl p-6 bg-white border border-gray-200 rounded-lg shadow  hover:bg-primary-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">

        <Text 
        :href="href" 
        :title="title"
        :desc="desc"
        />

        <RouterLink  v-if="!isForLogin" to="/main">
            <Button 
            :href="href" 
            :text="buttonText"
            />
        </RouterLink>

        <Button 
        v-else
        data-modal-target="authentication-modal" 
        data-modal-toggle="authentication-modal"
        :href="href" 
        :text="buttonText"
        />

        <LoginModal />

    </article>
</template>

// background_remover/src/components/HomeCard/Card.tsx
import Text from "./Text"
import Button from "./Button"
import LoginModal from "../LoginModal/Index"
import { Link } from "react-router-dom"

function Card({title, desc, buttonText, isForLogin = false, href}: {title: string, desc: string, buttonText: string, isForLogin: boolean, href: string}) {

    const isForLoginHandler = () => {
        if (!isForLogin) {
            return (
                <Link to="/main">
                    <Button 
                        text={buttonText}
                    />
                </Link>
            )
        } else {
            return (
                    <Button 
                    data-modal-target="authentication-modal" 
                    data-modal-toggle="authentication-modal"
                    text={buttonText}
                />
            )
        }
    }

  return (
    <>
        <article className="max-w-lg md:max-w-xl p-6 bg-white border border-gray-200 rounded-lg shadow  hover:bg-primary-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">

            <Text 
                href={href}
                title={title}
                desc={desc}
            />

            { isForLoginHandler() }
            
            <LoginModal />

        </article>
    </>
  )
}

export default Card
