// background_remover/src/components/Hero/Button.tsx
import { Link } from "react-router-dom"

function button({isPrimary, text}: {isPrimary: boolean, text: string}) {

  const IsPrimaryHandler = () => {
    if (isPrimary) {
      return (
        <Link to='/main' className="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">
          { text }
        </Link>
      )
    } else {
      return (
        <a data-modal-target="authentication-modal" data-modal-toggle="authentication-modal" className="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-primary-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
          { text }
        </a> 
      )
    }
  }

  return (
    <>
      {IsPrimaryHandler()}
    </>
  )
}

export default button

// frontend/src/components/Hero/components/Button.vue
<script>
    import { RouterLink } from 'vue-router';

    export default {
        props: {
            isPrimary: Boolean,
            text: String
        },
        components: {
            RouterLink
        }
    }
</script>

<template>
    <RouterLink v-if="isPrimary" to="/main" class="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">
        {{ text }}
        <svg class="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </RouterLink>
    <a v-else data-modal-target="authentication-modal" data-modal-toggle="authentication-modal" class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-primary-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
        {{ text }}
    </a> 
</template>
